export { default as HomeView } from './HomeView/HomeView.vue'
export { default as SearchView } from './SearchView/SearchView.vue'
export { default as RecipeView } from './RecipeView/RecipeView.vue'
export { default as AddRecipeView } from './AddRecipeView/AddRecipeView.vue'
export { default as SearchResultView } from './SearchResultView/SearchResultView.vue'
export { default as EditRecipeView } from './EditRecipeView/EditRecipeView.vue'
